# This is a basic workflow to help you get started with Actions

name: Build Samples Browser

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, vnext ]
  pull_request:
    branches: [ master, vnext ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            cache-dependency-path: browser/package-lock.json
            node-version: ${{ matrix.node-version }}
            cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./browser

      - name: Build the samples browser to ensure it compiles
        run: npm run build
        working-directory: ./browser
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
